FROM maven:3-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
COPY --from=build /target/dto-demo-0.0.1-SNAPSHOT.jar dto-demo.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","dto-demo.jar" ]